spring:
  batch:
    jdbc:
      initialize-schema: never
---
spring:
  config:
    activate:
      on-profile: local

  batch:
    job:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: dev

  batch:
    job:
      name: crawlingJob
      enabled: true
