spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/idle?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:mysql}
  jpa:
    open-in-view: false
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

auth:
  jwt:
    issuer: ${JWT_ISSUER:idle}
    access:
      expire-seconds: ${JWT_ACCESS_EXPIRE_SECONDS}
      secret: ${JWT_ACCESS_SECRET_SIGNATURE}
    refresh:
      expire-seconds: ${JWT_REFRESH_EXPIRE_SECONDS}
      secret: ${JWT_REFRESH_SECRET_SIGNATURE}

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
        hibernate.format_sql: true
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
