version: '3.8'
services:
  spring:
    image: public.ecr.aws/${ECR_REGISTRY_ALIAS}/caremeet:${VERSION:-latest}
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      - VERSION=${VERSION:-latest}
      - SPRING_PROFILES_ACTIVE=dev
    pull_policy: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - redis-caremeet-net
      - mysql-caremeet-net

  mysql:
    image: mysql:8.0.33
    container_name: mysql_dev
    environment:
      MYSQL_DATABASE: caremeet
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    networks:
      - mysql-caremeet-net

  redis:
    image: redis:7.2.5
    container_name: redis_dev
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: [ "redis-server", "--requirepass", "$REDIS_PASSWORD" ]
    volumes:
      - redis-volume:/data
    restart: unless-stopped
    networks:
      - redis-caremeet-net

networks:
  mysql-caremeet-net:
    driver: bridge
  redis-caremeet-net:
    driver: bridge

volumes:
  mysql-volume:
  redis-volume:
