version: '3.8'
services:
  spring:
    image: public.ecr.aws/${ECR_REGISTRY_ALIAS}/idle-ecr:${VERSION:-latest}
    volumes:
      - mysql-volume:/var/lib/mysql
      - /home/ubuntu/usr/bin/chromedriver:/usr/bin/chromedriver
      - /home/ubuntu/usr/bin/chromium-browser:/usr/bin/chromium-browser
    environment:
      - VERSION=${VERSION:-latest}
      - SPRING_PROFILES_ACTIVE=dev
    entrypoint: ["/bin/sh", "-c", "chmod +x /usr/bin/chromedriver /usr/bin/chromium-browser && java -jar /app.jar"]
    pull_policy: always
    env_file:
      - .env
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    network_mode: "host"

  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: idle
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    network_mode: "host"

  redis:
    image: redis:7.2.5
    container_name: redis_dev
    ports:
      - "6379:6379"
    network_mode: "host"

volumes:
  mysql-volume:
