auth:
  jwt:
    issuer: ${JWT_ISSUER:idle}
    access:
      expire-seconds: ${JWT_ACCESS_EXPIRE_SECONDS}
      secret: ${JWT_ACCESS_SECRET_SIGNATURE}
    refresh:
      expire-seconds: ${JWT_REFRESH_EXPIRE_SECONDS}
      secret: ${JWT_REFRESH_SECRET_SIGNATURE}
