auth:
  jwt:
    issuer: ${JWT_ISSUER:idle}
    access:
      carer:
        expire-seconds: ${JWT_CARER_ACCESS_EXPIRE_SECONDS}
      center:
        expire-seconds: ${JWT_CENTER_ACCESS_EXPIRE_SECONDS}
      secret: ${JWT_ACCESS_SECRET_SIGNATURE}
    refresh:
      carer:
        expire-seconds: ${JWT_CARER_REFRESH_EXPIRE_SECONDS}
      center:
        expire-seconds: ${JWT_CENTER_REFRESH_EXPIRE_SECONDS}
      secret: ${JWT_REFRESH_SECRET_SIGNATURE}
